global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      monitor: 'Alertmanager'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
    - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #third state whether this is testing external or internal network
        target_label: routing
        replacement: $3
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #fourth is which switch/router the device is connected to.
        target_label: switching
        replacement: $4
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [icmp_ipv4]  # Look for a icmp response.
    static_configs:
      - targets:
        - google.com
        - github.com
        - apple.com
        - 165.166.157.253
        - 204.116.220.2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # This is your blackbox exporter.

  - job_name: 'nodeexp'
    static_configs:
    - targets: ['nodeexp:9100']

  - job_name: 'snmp_mikrotik'
    static_configs:
      - targets:
        - "100.64.0.1"
    metrics_path: "/snmp"
    params:
      module: [mikrotik]
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.64.0.3:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'snmp_ruckus'
    static_configs:
      - targets:
        - "100.64.0.2"
    metrics_path: "/snmp"
    params:
      module: [ruckus]
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.64.0.3:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'mikrotik_test'
    static_configs:
      - targets:
        - "100.64.0.1"
    metrics_path: "/snmp"
    params:
      module: [mikrotik_test]
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.64.0.3:9116  # The SNMP exporter's real hostname:port.
