{
 "title": "internet-connection",
 "tags": [ "ping" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "WAN Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=\"1\", job=\"snmp_mikrotik\"}[5m]) * 8 / 1048576",
     "legendFormat": "WAN Down"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=\"1\", job=\"snmp_mikrotik\"}[5m]) * 8 / 1048576 * -1",
     "legendFormat": "WAN Up"
    }
   ]
  },
  {
   "title": "Mikrotik LAN Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifIndex=~\"[2-4]\", job=\"snmp_mikrotik\"}[2m]) * 8 / 1048576",
     "legendFormat": "{{ifName}} Down"
    },
    {
     "expr": "rate(ifHCInOctets{ifIndex=~\"[2-4]\", job=\"snmp_mikrotik\"}[2m]) * 8 / 1048576 *-1",
     "legendFormat": "{{ifName}} Up"
    }
   ]
  },
  {
   "title": "WLAN Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifIndex=~\"2[8-9]\", job=\"snmp_ruckus\"}[1m])*8 / 1048576",
     "legendFormat": "{{ifName}} Down"
    },
    {
     "expr": "rate(ifHCInOctets{ifIndex=~\"2[8-9]\", job=\"snmp_ruckus\"}[1m])*-1*8 / 1048576",
     "legendFormat": "{{ifName}} Up"
    }
   ]
  },
  {
   "title": "WLAN Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(ruckusUnleashedSystemStatsWLANTotalTxRetry[1m])",
     "legendFormat": "TxRetry"
    },
    {
     "expr": "irate(ruckusUnleashedSystemStatsWLANTotalTxDroppedPkt[1m])",
     "legendFormat": "TxDroppedPkt"
    },
    {
     "expr": "irate(ruckusUnleashedSystemStatsWLANTotalTxFail[1m])",
     "legendFormat": "TxFail"
    },
    {
     "expr": "irate(ruckusUnleashedSystemStatsWLANTotalTxErrFrm[1m])",
     "legendFormat": "TxErrFrm"
    },
    {
     "expr": "irate(ruckusUnleashedSystemStatsWLANTotalRxErrFrm[1m])",
     "legendFormat": "RxErrFrm"
    }
   ]
  },
  {
   "title": "WLAN Stations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ruckusUnleashedSystemStatsNumSta",
     "legendFormat": "Stations"
    }
   ]
  },
  {
   "title": "Uptime (HTTP)",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime (ICMP)",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-icmp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "graph",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"blackbox-http\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}